### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'a'

### ISSUE THREAD

**Issue by futetete** [Euclid-Jie/Euclidweibo-search#7]
您好，麻烦您看下我出现的问题，不太会使用python，谢谢您！
刚开始是用V3进行爬虫，然后ip封禁后就转向使用V1，但是刚用就出现这样的报错：AttributeError: 'NoneType' object has no attribute 'a'。
全部的是这样的：
文件将存储在: D:\python\Euclidweibo-search-master\Weibo\流.csv
> get 流 blog data begin ... 
>> time span: 2023-01-28-0 - 2023-02-10-0
  0%|          | 0/50 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\python\Euclidweibo-search-master\WeiboClassV1.py", line 200, in <module>
    demoClass.main_get('流浪地球', timeBegin, timeEnd)
  File "D:\python\Euclidweibo-search-master\WeiboClassV1.py", line 185, in main_get
    min_time_dt = self.get_all_pages_data()
  File "D:\python\Euclidweibo-search-master\WeiboClassV1.py", line 152, in get_all_pages_data
    data_json = future.result()
  File "D:\anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\anaconda3\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\anaconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\python\Euclidweibo-search-master\WeiboClassV1.py", line 79, in get_single_weibo_json
    mblogid = re.findall('(?<=/)[A-Za-z0-9]+(?=\?)',blog.find('div', 'from').a['href'])[0]
AttributeError: 'NoneType' object has no attribute 'a'

进程已结束,退出代码1
![image](https://user-images.githubusercontent.com/132832803/236685087-7bdd5675-f9cd-4232-8805-0a1e137611eb.png)

**Comment by Euclid-Jie** [comment]
看样子应该是，网页源码发生了改动，预计两天内修复

**Comment by Euclid-Jie** [comment]
不过我刚刚用你的参数试了一下，并未复现你的bug。建议你更新cookie，并保证网络通畅后重试一下
![image](https://user-images.githubusercontent.com/71357995/236685779-5f663e88-5b4e-43b2-924d-6ada6ee9381e.png)

**Comment by futetete** [comment]
> 不过我刚刚用你的参数试了一下，并未复现你的bug。建议你更新cookie，并保证网络通畅后重试一下 ![image](https://user-images.githubusercontent.com/71357995/236685779-5f663e88-5b4e-43b2-924d-6ada6ee9381e.png)

我更新了cookie，网络用校园网和流量都试过了，还是出现这样的报错T^T

**Comment by Euclid-Jie** [comment]
> > 不过我刚刚用你的参数试了一下，并未复现你的bug。建议你更新cookie，并保证网络通畅后重试一下 ![image](https://user-images.githubusercontent.com/71357995/236685779-5f663e88-5b4e-43b2-924d-6ada6ee9381e.png)
> 
> 我更新了cookie，网络用校园网和流量都试过了，还是出现这样的报错T^T

那很奇怪了，我怀疑cookie问题，加我QQ：2379928684，详细聊一下
